spring:
  data:
    mongodb:
      username: root
      password: example
      host: localhost
      authentication-database: admin
      database: payment
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, custom
  
  info:
    git:
      enabled: true
      mode: full
    os:
      enabled: true
    java:
      enabled: true
  endpoint:
    beans:
      cache:
        time-to-live: "10s"
    caches:
      enabled: false
    custom:
      enabled: true
      cache:
        time-to-live: "10s"
    metrics:
      enabled: true
    info:
      enabled: true
    health:
      enabled: true
      show-components: always
      show-details: always
server:
  port: 9000

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG