spring:
  data:
    mongodb:
      username: root
      password: example
      host: localhost
      authentication-database: admin
      database: payment

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
      show-components: always
      show-details: always