spring:
  data:
    mongodb:
      username: root
      password: example
      host: localhost
      authentication-database: admin
      database: payment
management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    git:
      enabled: true
      mode: full
    os:
      enabled: true
    java:
      enabled: true
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      show-components: always
      show-details: always
server:
  port: 9000